<a href="https://colab.research.google.com/github/Rishirajyadav-25/daily-quotes/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from matplotlib import pyplot as plt

In [ ]:

# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("==== Zomato sales analysis ==== ")
print("\n Sales data shape", sales_data.shape)
print("\n Sample data for 1st 3 restau: \n", sales_data[:3])

==== Zomato sales analysis ==== 

 Sales data shape (5, 5)

 Sample data for 1st 3 restau: 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [ ]:
zeros = np.zeros((3,3))
print(zeros)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
num_1D = np.array([1,2,3,4,5])*2
print("Numpy 1D multiplication : \n",num_1D)

Numpy 1D multiplication : 
 [ 2  4  6  8 10]


In [ ]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
full = np.full((3,3),5)
print("Full in numpy \n",full)

randoms = np.random.random((4,4))
print("Random in numpy\n",randoms)

sequences = np.arange(1,10,2)
print("Sequences in numpy\n",sequences)

Full in numpy 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
Random in numpy
 [[0.92684266 0.90032452 0.40417621 0.79797097]
 [0.83947719 0.41815157 0.48260403 0.46570902]
 [0.1267886  0.60136139 0.80433697 0.81105042]
 [0.54831443 0.05652652 0.54829458 0.61091134]]
Sequences in numpy
 [1 3 5 7 9]


### Array Properties

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

print("\nShape :",arr.shape)
print("\nDimension :", arr.ndim)
print("\nSize : ",arr.size)
print("\n Dtype : ",arr.dtype)

[[1 2 3 4]
 [5 6 7 8]]

Shape : (2, 4)

Dimension : 2

Size :  8

 Dtype :  int64


In [ ]:
arr = np.arange(12)
print("Original Array : ",arr)

reshaped = np.reshape((arr),(12,1))
print("Reshaped Array : \n",reshaped)

flattened = reshaped.flatten()
print("Flattened Array : \n",flattened)

Original Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array : 
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
Flattened Array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:

# return view instead of the copy
revaled = reshaped.ravel()
print("Revaled Array : \n",revaled)

Revaled Array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# Transpose of an array
print("Original Array : \n",reshaped)
transposed = reshaped.transpose()
print(" the transpose matrix is : \n",transposed)
print("\n Transposed Array : \n",transposed)

 the transpose matrix is : 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
transposed = np.transpose(arr)
print(transposed)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


#### Indexing

In [ ]:
arr_1d =np.array([1,2,3,4,5,6,7,8,9,10])
print(arr_1d)
print("basic slicing:",arr_1d[2:7])
print("slicing with step:",arr_1d[2:7:2])


[ 1  2  3  4  5  6  7  8  9 10]
basic slicing: [3 4 5 6 7]
slicing with step: [3 5 7]


In [ ]:
#sorting
arr_1d = np.array([1,6,8,2,5,1])
print("sorted numpy array :",np.sort(arr_1d))

sorted numpy array : [1 1 2 5 6 8]


In [ ]:
#sorting 2D array
arr_2d = np.array([[3,6],[2,5],[1,4]])
print("sorted numpy array :",np.sort(arr_2d,axis=1))  # axis=0 means column and axis=1 means row

sorted numpy array : [[3 6]
 [2 5]
 [1 4]]


In [ ]:
# Adding and removing
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print("addition of the array :",np.add(arr1,arr2))
print("subtraction of the array :",np.subtract(arr1,arr2))

print("Concatenation of the numpy array :",np.concatenate((arr1,arr2)))

addition of the array : [5 7 9]
subtraction of the array : [-3 -3 -3]
Concatenation of the numpy array : [1 2 3 4 5 6]
